### ISSUE TITLE
Convert into a PyPI Package (pip)

### ISSUE THREAD

**Issue by kingroryg** [saru95/xkcd#2]
Installation needs to happen using pip . :)

**Comment by 3onyc** [comment]
Assuming you mean PyPI (Python Package Index) instead of PyPy (Alternative python implementation). Anyway, on it!

**Comment by kingroryg** [comment]
Oh ! Yeah . Thanks !

**Comment by ronalddas** [comment]
Can I try too? It will be a good way to learn to make my own Python package

**Comment by 3onyc** [comment]
@ronalddas fine with me, check out the [setuptools documentation](https://setuptools.readthedocs.io/en/latest/) for a good starting point.

**Comment by kingroryg** [comment]
Yeah ! Go ahead .

**Comment by 3onyc** [comment]
Suggest closing this so it no longer shows up searching for hacktoberfest, feel free to tag the other issues with it though ;)
